name: 🚀 Déploiement OVH via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Déploiement FTP sur OVH
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /www/
          local-dir: ./
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/_local/**
            **/php/config.php
